### ISSUE TITLE
Setting the report property to hidden

### ISSUE THREAD

**Issue by erajendar** [Microsoft/ReportingServicesTools#110] opened 2017-11-15 12:36 UTC
I want to check the feature
Hi - I want to set the report visibility property to hidden.  Is there any existing property available for it.

Regards,
Rajendar

**Comment by nschonni** [comment] 2017-11-16 05:00
Duplicate of #76

**Comment by jtarquino** [comment] 2018-01-03 00:41
Duplicate of #76

**Closed by jtarquino** 2018-01-03 00:41 UTC
Labels: enhancement
