### ISSUE TITLE
Bug with Set-RsSubscription

### ISSUE THREAD

**Issue by vishyonline** [Microsoft/ReportingServicesTools#72] opened 2017-09-08 10:58 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
When copying subscriptions using Get-RsSubscription and Set-RsSubscription powershell scripts, there is a type mismatch for ExtensionSettings object. Screenshot attached.
<img width="576" alt="subscription copy" src="https://user-images.githubusercontent.com/31765650/30208767-972672c2-94b2-11e7-9a47-835e9c908372.png">

**What is the expected behavior?**

**Which versions of Powershell and which OS are affected by this issue? Did this work in previous versions of our scripts?**

**Comment by jtarquino** [comment] 2017-09-08 16:15
@ClaudioESSilva have you seen it?

**Comment by ClaudioESSilva** [comment] 2017-09-11 14:56
No, I didn't.

@vishyonline can you provide more details?
What is your source and target SSRS versions?

**Comment by vishyonline** [comment] 2017-09-12 04:14
Thank you both for looking into this. 

Both my source are target SSRS is on SQL 2016. Please let me know if you need any more details.

**Comment by petjoe** [comment] 2017-09-12 13:27
I get the same error message when i try to save a subscription to disk and load it back:
```
Get-RsSubscription |  Export-Clixml
Import-Clixml | Set-RsSubscription 
```
Not shure if this is a serialization issue or is the same thing as above.

**Comment by ClaudioESSilva** [comment] 2017-09-18 17:31
@vishyonline I can't reproduce the error. Can you try to do that one a single instance. Like copying the Subscription from one Folder/Report to another Folder2/Report2. 
Do you get the same error? Trying to eliminate variables :-)

Also can be some kind of subscription configuration that I haven't test before.

**Comment by markwragg** [comment] 2017-10-04 10:47
I am working on an amendment to the module that deals with the serialization issue by adding an Import-RsSubscription cmdlet that recreates the .ExtensionSettings property so that its a valid object for use with Set-RsSubscription.

https://github.com/Microsoft/ReportingServicesTools/compare/master...markwragg:master

**Comment by markwragg** [comment] 2017-10-04 13:29
Per PR https://github.com/Microsoft/ReportingServicesTools/pull/79 I've now amended the Set-RsSubscription cmdlet so that it recreates the .DeliverySettings property for a Deserialized object and removed the Import/Export-RsSubscription cmdlets that I proposed adding.

As a result if this PR is merged you should then be able to:

```
Get-RsSubscription -Path /some/path | Export-CliXML .\somefile.xml
Import-CliXML .\somefile.xml | Set-RsSubscription -Path /some/path

```
Successfully.

This PR also contains a new `New-RsSubscription` cmdlet which is useful to anyone looking to create subscriptions from scratch directly with PowerShell.

**Comment by markwragg** [comment] 2017-10-05 15:19
I've discovered today that Get-RsSubscription and Set-RsSubscription were not handling Data Driven subscriptions successfully as they require using different underlying SOAP methods. I'm working on fixes for this.

**Comment by petjoe** [comment] 2017-10-16 09:18
@markwragg: that's awesome, thank you very much

**Comment by parthsha** [comment] 2017-12-13 04:59
It seems like this issue is resolved, so I am going to go ahead and close it. Please feel free to reopen it if that is not the case.

**Closed by parthsha** 2017-12-13 04:59 UTC
